//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce01DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Inventories = new HashSet<Inventory>();
        }
    
        public int ProductId { get; set; }
        public int CompanyId { get; set; }
        public int CategoryId { get; set; }
        public string Description { get; set; }
        public string BarCode { get; set; }
        public decimal VendorPrice { get; set; }
        public string VendorProductCode { get; set; }
        public decimal Price { get; set; }
        public int TaxId { get; set; }
        public string Image { get; set; }
        public string Remarks { get; set; }
        public double ReorderPoint { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory> Inventories { get; set; }
        public virtual Tax Tax { get; set; }
    }
}
